const ACCEPTED_EXTENSIONS = [".mp3", ".mp4"] as const;
const ACCEPTED_MIME_TYPES = ["audio/mpeg", "audio/mp3", "video/mp4"] as const;

export function isAcceptedMediaFile(file: File): boolean {
  const extension = file.name.slice(file.name.lastIndexOf(".")).toLowerCase();
  if (ACCEPTED_EXTENSIONS.includes(extension as (typeof ACCEPTED_EXTENSIONS)[number])) {
    return true;
  }
  return ACCEPTED_MIME_TYPES.includes(file.type as (typeof ACCEPTED_MIME_TYPES)[number]);
}

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export function transcriptionFileName(originalName: string): string {
  const baseName = originalName.replace(/\.[^.]+$/, "");
  return `${baseName}.txt`;
}

/**
 * Mock transcription. Replace this with the real API call when ready.
 */
export async function transcribeFile(
  file: File,
  onProgress?: (progress: number) => void,
): Promise<string> {
  const steps = 20;

  for (let step = 1; step <= steps; step++) {
    await new Promise((resolve) => setTimeout(resolve, 120));
    onProgress?.(Math.round((step / steps) * 100));
  }

  const mediaType = file.name.toLowerCase().endsWith(".mp4") ? "video" : "audio";

  return [
    `Transcription for: ${file.name}`,
    `Media type: ${mediaType}`,
    `Processed at: ${new Date().toISOString()}`,
    "",
    "This is placeholder text generated by the UI mock.",
    "Connect transcribeFile() to your transcription API to replace this output.",
  ].join("\n");
}

export function downloadTranscription(text: string, fileName: string): void {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}
